# Generated by Django 4.2.18 on 2025-04-23 16:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='profile_image',
            new_name='profilee_image',
        ),
        migrations.AddField(
            model_name='collaboraterequest',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
